<BlackButton>
    text: ""

    size_hint: None, None
    size: 250, 30
    md_bg_color: 0,0,0,1
    pos_hint: {"center_x": .5}
    radius: [15]

    MDFloatLayout:
#        md_bg_color: 1,1,1,.3
        MDLabel:
#            md_bg_color: 1,1,1,.3
            adaptive_size: True
            text: root.text
            theme_text_color: "Custom"
            text_color: 1,1,1,1
            pos_hint: {"center_x": .5, "center_y": .55}
#            halign: "center"
            bold: True
